connector.name=hive
hive.metastore=file
hive.metastore.catalog.dir=file:///data/metastore
hive.non-managed-table-writes-enabled=true
hive.parquet.use-column-names=true
hive.storage-format=PARQUET
hive.allow-drop-table=true
